### ISSUE TITLE
不能取消监听广播

### ISSUE THREAD

**Issue by xiaofengshen** [Softtanck/RAMessage#16]
当我 在Activity销毁时
  RaClientApi.INSTANCE.destroyAllResources()
  不能断开连接 和取消广播的监听，导致重复注册和重复接收到广播

**Comment by Softtanck** [comment]
I think it's a bug, I'll fix it later.

**Comment by Softtanck** [comment]
@xiaofengshen Please try with `implementation 'com.github.Softtanck:RAMessage:2.0.0-RC3' ` and it has been fixed in this the verison, Thanks.
